
package at.willhaben.willtest.generated;

import java.io.FileInputStream;
import java.util.Date;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;


/**
 * <p>Test suite generated by at.willhaben.willtest.maven.utils.SuiteGeneratingRunListener based on execution order in surefire/failsafe maven plugin. Below you see the classes in order of execution and in the second column the test method order inside the class file.</p>
 * <table>
 * <tr>
 * 	<th>Test class</th><th>Test method and display name</th>
 * </tr>
 * <tr>
 * 	<td rowspan="2">java.lang.Long</td><td>Method 'methodA', DisplayName: 'methodA[alma]'</td>
 * </tr>
 * <tr>
 * 	<td>Method 'methodC', DisplayName: 'methodC[alma]'</td>
 * </tr>
 * <tr>
 * 	<td>java.util.Date</td><td>Method 'methodB', DisplayName: 'methodB[alma]'</td>
 * </tr>
 * <tr>
 * 	<td>java.sql.Date</td><td>Method 'methodBB', DisplayName: 'methodBB[alma]'</td>
 * </tr>
 * <tr>
 * 	<td>java.io.FileInputStream</td><td>Method 'methodX', DisplayName: 'methodX[alma]'</td>
 * </tr>
 * </table>
 * 
 */
@RunWith(Suite.class)
@Suite.SuiteClasses({
    Long.class,
    Date.class,
    java.sql.Date.class,
    FileInputStream.class
})
public class Suite_20170211_142342 {


}
